### ISSUE TITLE
Explore use of Rancher (RKE2) in deployment and auto-scaling pods

### ISSUE THREAD

**Issue by Sanjay-George** [Sanjay-George/nick-name-generator#13]
## RKE
- [ ] Try RKE deployment on AWS : https://github.com/LukeMwila/bootstrap-rke-cluster-in-aws

## RKE2
RKE2 is the standard now, uses containerd runtime instead of Docker
* https://github.com/rancherfederal/rke2-aws-tf
* https://docs.rke2.io/
 
### Steps
- [x] Modify terraform script to handle changes for AWS academy

- [x] Run terraform to provision RKE cluster

**Incase of issue with deleting internet gateway, delete the ALB**
https://stackoverflow.com/questions/37232965/issue-when-trying-to-delete-vpc-and-network-interface

- [x] Create alias to read the kubeconfig 
![image](https://user-images.githubusercontent.com/10389062/183345709-c3028262-9b09-4bcd-b20e-ed1f13892ba0.png)

- [x] Deploy nick name app

### Todo - Create new stories
- [ ] Figure out how to get public IP for all Loadbalancer services. Currently external ip remains in `<PENDING>` state
* This worked, but after very long time. Also, service discovery doesn't seem to be working on path `/nick-name`
![Image](https://user-images.githubusercontent.com/10389062/183355148-7105b684-8e54-4a2c-9a57-1a7cdaff9e1b.png)

- [ ] Specify SSH key for the cluster `vockey` 
- [ ] Deploy dashboard
* https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
* https://k21academy.com/docker-kubernetes/kubernetes-dashboard/
- [ ] Check auto scaling parameters. Tune if needed
- [ ] Understand nodepool vs server. Adjust count for HA
- [ ] Check the availability zones deployment logic. Fix, if needed.

**Comment by Sanjay-George** [comment]
**Incase of issue with deleting internet gateway, delete the ALB**
https://stackoverflow.com/questions/37232965/issue-when-trying-to-delete-vpc-and-network-interface



![Image](https://user-images.githubusercontent.com/10389062/185145887-9167874d-40c0-4d90-9d7d-f67ace7023ce.png)
