### ISSUE TITLE
Deploy nick-name-generator to GKE

### ISSUE THREAD

**Issue by Sanjay-George** [Sanjay-George/nick-name-generator#18]
### Todo
- [x] Quickly go through GKE concepts
- [x] Deploy nick-name-gen as it is on GKE (using current API gateway) using the Console
- [x] Test and ensure it works properly
- [x] ~~Write `tf` for creating GKE cluster and deploying~~
