### ISSUE TITLE
Improve RKE2 cluster deployment on AWS ⭐

### ISSUE THREAD

**Issue by Sanjay-George** [Sanjay-George/nick-name-generator#7]
### Todo - Create separate stories if needed
- [ ] Figure out how to get public IP for all Loadbalancer services. Currently external ip remains in `<PENDING>` state
* This worked, but after very long time. Also, service discovery doesn't seem to be working on path `/nick-name`
![Image](https://user-images.githubusercontent.com/10389062/183355148-7105b684-8e54-4a2c-9a57-1a7cdaff9e1b.png)

- [ ] Specify SSH key for the cluster `vockey` 

- [ ] Deploy dashboard
* https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
* https://k21academy.com/docker-kubernetes/kubernetes-dashboard/

- [ ] Check auto scaling parameters. Tune if needed

- [ ] Understand nodepool vs server. Adjust count for HA

- [ ] Check the availability zones deployment logic. Fix, if needed.

**Comment by Sanjay-George** [comment]
alias k8="kubectl --kubeconfig=$HOME/rke2-aws-tf/examples/cloud-enabled/rke2.yaml"

**Comment by Sanjay-George** [comment]
Too much time taken for creating services and getting deployments ready. So, trying with more nodes in cluster (5 generic, 3 master)
