### ISSUE TITLE
Build the app on local kube cluster

### ISSUE THREAD

**Issue by Sanjay-George** [Sanjay-George/nick-name-generator#9]
## Todo
- [x] Create a random name generator - 2/3 microservices
Format: {adjective}-{color}-{animal}
eg: annoying-blue-panda

- [x] Create one endpoint `Get` that returns static data  `{ name, server }`

- [x] Set folder structure according to best standards - monolithic repo

- [x] Set k8 services and deployments for web service to make calls to microservices 

- [x] Test on local k8s

- [x] Build animal MS to complete the development 
 

## Articles

1. https://expressjs.com/en/guide/routing.html#route-parameters
2. https://nodejs.org/api/http2.html
3. https://learn.hashicorp.com/tutorials/consul/service-mesh
